CREATE TABLE Post(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  content TEXT(650000) NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Category(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE post_category(
  post_id INT UNSIGNED NOT NULL,
  Category_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (post_id, Category_id),
  CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES Post(id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES Category (id) ON DELETE CASCADE ON UPDATE RESTRICT,
);

CREATE TABLE user(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);